# Sample user
# username: allen
# password: allenc
u = User.new
u.login = "allen"
u.email = "example@example.com"
u.crypted_password = "44d1f9bd456ae2fb8558b1c4877227fbb16cf4e9"
u.salt = "756b488e613c4899fa16bf3e6c350e39c626296d"
u.created_at = Time.now
u.activated_at = Time.now
u.updated_at = Time.now

Word.create :word => "abate", :definition => "to lessen to subside "
Word.create :word => "abdication", :definition => "giving up control authority "
Word.create :word => "aberration", :definition => "straying away from what is normal "
Word.create :word => "abet", :definition => "help/encourage smb (in doing wrong) "
Word.create :word => "abeyance", :definition => "suspended action "
Word.create :word => "abhor", :definition => "to hate to detest "
Word.create :word => "abide", :definition => "be faithful to endure "
Word.create :word => "abjure", :definition => "promise or swear to give up "
Word.create :word => "abraded", :definition => "rubbed off worn away by friction "
Word.create :word => "abrogate", :definition => "repeal or annul by authority "
Word.create :word => "abscond", :definition => "to go away suddenly (to avoid arrest) "
Word.create :word => "abstruse", :definition => "difficult to comprehend obscure "
Word.create :word => "abut", :definition => "border on "
Word.create :word => "abysmal", :definition => "bottomless extreme "
Word.create :word => "acarpous", :definition => "effete no longer fertile worn out "
Word.create :word => "acclaimed", :definition => "welcomed with shouts and approval "
Word.create :word => "accolade", :definition => "praise approval "
Word.create :word => "accretion", :definition => "the growing of separate things into one "
Word.create :word => " accrue ", :definition => " accumulate"
Word.create :word => "adamant", :definition => "kind of stone inflexible "
Word.create :word => "admonitory", :definition => "containing warning "
Word.create :word => "adorn", :definition => "add beauty decorate "
Word.create :word => "adulteration", :definition => "making unpure poorer in quality "
Word.create :word => "affable", :definition => "polite and friendly "
Word.create :word => "affinity", :definition => "close connection relationship "
Word.create :word => "aggravate", :definition => "make worse irritate "
Word.create :word => "agile", :definition => "active quick-moving "
Word.create :word => "agog", :definition => "eager/excited "
Word.create :word => "ail", :definition => "trouble be ill "
Word.create :word => "alacrity", :definition => "eager and cheerful readiness "
Word.create :word => "alcove", :definition => "recess/partially enclosed place "
Word.create :word => " ale", :definition => " fermented alcoholic beverage similar to but heavier than beer"
Word.create :word => " aleck", :definition => " one who considers himself smarter than others"
Word.create :word => "allegiance", :definition => "duty support loyalty "
Word.create :word => "alleviate", :definition => "make (pain) easier to bear "
Word.create :word => "alloy", :definition => "to debase by mixing with something inferior "
Word.create :word => "aloof", :definition => "reserved indifferent "
Word.create :word => "amalgamate", :definition => "mix combine unite societies "
Word.create :word => "ambidextrous", :definition => "able to use the left hand or the right equally well "
Word.create :word => "ambiguous", :definition => "doubtful uncertain "
Word.create :word => "ambivalent", :definition => "having both of two contrary meanings "
Word.create :word => "ambrosial", :definition => "extremely pleasing to taste "
Word.create :word => "ameliorate", :definition => "improve make better "
Word.create :word => "amortize", :definition => "end (a debt) by setting aside money "
Word.create :word => "anguish", :definition => "severe suffering "
Word.create :word => "animosity", :definition => "strong dislike "
Word.create :word => "antidote", :definition => "medicine used against a poison or a disease "
Word.create :word => "antithetical", :definition => "direct opposing "
Word.create :word => "apartheid", :definition => "brutal racial discrimination "
Word.create :word => "aplomb", :definition => "self-confidence "
Word.create :word => "apostate", :definition => "one who abandons long-held religious or political convictions "
Word.create :word => "apotheosis", :definition => "deification glorification to godliness "
Word.create :word => "appease", :definition => "make quiet or calm "
Word.create :word => "apprehensive", :definition => "grasping understanding fear unhappy feeling about future "
Word.create :word => "apprise", :definition => "give notice to inform "
Word.create :word => "approbation", :definition => "approval "
Word.create :word => "apropos", :definition => "appropriate to the situation apt "
Word.create :word => "apt", :definition => "well-suited quick-witted "
Word.create :word => "arabesque", :definition => "a complex ornate design "
Word.create :word => "arboreal", :definition => "of connected with trees "
Word.create :word => "ardor", :definition => "enthusiasm "
Word.create :word => "arduous", :definition => "steep difficult ascent laborious "
Word.create :word => "argot", :definition => "jargon slang "
Word.create :word => "arrant", :definition => "in the highest degree "
Word.create :word => "arrogance", :definition => "proud superior manner of behaviour "
Word.create :word => "articulate", :definition => "speak distinctly connect by joints "
Word.create :word => "ascend", :definition => "go or come up "
Word.create :word => "ascertain", :definition => "get to know "
Word.create :word => "ascetic", :definition => "practicing self-denial austere stark "
Word.create :word => "ascribe", :definition => "consider to be the origin of or belonging to "
Word.create :word => "aseptic", :definition => "surgically clean "
Word.create :word => "asperity", :definition => "roughness harshness ill temper irritability "
Word.create :word => "aspersion", :definition => "slander "
Word.create :word => "assail", :definition => "with attack violently "
Word.create :word => "assiduous", :definition => "diligent hard-working sedulous "
Word.create :word => "assuage", :definition => "make something (pain desire) less "
Word.create :word => "asterisk", :definition => "the mark * (e.g.. omitted letters) "
Word.create :word => "astringent", :definition => "substance that shrinks "
Word.create :word => "astute", :definition => "clever quick at seeing to get an advantage "
Word.create :word => "atonement", :definition => "repayment death of Jesus "
Word.create :word => "attenuate", :definition => "make thin. weaken enervate "
Word.create :word => "attune", :definition => "bring into harmony "
Word.create :word => "audacious", :definition => "daring foolishly bold impudent "
Word.create :word => "augury", :definition => "omen sign "
Word.create :word => "august", :definition => "majestic venerable "
Word.create :word => "auspicious", :definition => "favorable successful prosperous "
Word.create :word => "austere", :definition => "severely moral and strict simple and plain "
Word.create :word => "auxiliary", :definition => "helping supporting "
Word.create :word => "aver", :definition => "affirm assert prove justify "
Word.create :word => "aversion", :definition => "strong dislike "
Word.create :word => "avid", :definition => "eager greedy "
Word.create :word => "avow", :definition => "admit. Declare openly "
Word.create :word => "baleful", :definition => "harmful ominous causing evil "
Word.create :word => "balk", :definition => "obstacle purposely to get on the way of "
Word.create :word => "baneful", :definition => "causing harm or ruin pernicious destructive "
Word.create :word => "barrage", :definition => "artificial obstacle built across a river "
Word.create :word => "barren", :definition => "not good enough unable to have young ones without value "
Word.create :word => "bask", :definition => "in enjoy warmth and light "
Word.create :word => "beatify", :definition => "to bless make happy or ascribe a virtue to "
Word.create :word => "bedizen", :definition => "to adorn especially in a cheap showy manner "
Word.create :word => "belabor", :definition => "beat hard "
Word.create :word => "bellicose", :definition => "belligerent pugnacious warlike "
Word.create :word => "belligerent", :definition => "(person nation) waging war "
Word.create :word => "benefactor", :definition => "person who has given help "
Word.create :word => "benevolence", :definition => "wish or activity in doing good "
Word.create :word => "benign", :definition => "kind and gentle mild (climate) "
Word.create :word => "bequest", :definition => "arrangement to give something at death "
Word.create :word => "berate", :definition => "scold sharply "
Word.create :word => "bereft", :definition => "rob or dispossess of something (material) "
Word.create :word => "bewilder", :definition => "puzzle confuse "
Word.create :word => "bigot", :definition => "stubborn narrow-minded person "
Word.create :word => "bilge", :definition => "bulge the protuberance of a cask "
Word.create :word => "blandishment", :definition => "flattery coaxing "
Word.create :word => "blandness", :definition => "polite manner comforting uninteresting "
Word.create :word => "blatant", :definition => "noisy and rough "
Word.create :word => "blithe", :definition => "cheerful casual carefree "
Word.create :word => "bogus", :definition => "sham counterfeit not genuine "
Word.create :word => "boisterous", :definition => "loud noisy rough lacking restraint "
Word.create :word => "bolster", :definition => "give greatly needed support "
Word.create :word => "boorish", :definition => "crude offensive rude "
Word.create :word => "brash", :definition => "hasty rush cheeky saucy "
Word.create :word => "brass", :definition => "yellow metal (mixing copper and zinc) "
Word.create :word => "brazen", :definition => "made of brass "
Word.create :word => "breach", :definition => "opening broken place breaking "
Word.create :word => "brittle", :definition => "easily broken "
Word.create :word => "broach", :definition => "bring up announce begin to talk about "
Word.create :word => "brook", :definition => "to tolerate endure "
Word.create :word => "buoyant", :definition => "able to float light-hearted "
Word.create :word => "burgeon", :definition => "grow forth send out buds "
Word.create :word => "burnish", :definition => "to polish rub to a shine "
Word.create :word => "cabal", :definition => "a scheme or plot a group of plotters "
Word.create :word => "cadge", :definition => "to beg to get by begging "
Word.create :word => "cajole", :definition => "use flattery or deceit to persuade "
Word.create :word => "calipers", :definition => "metal supports attached to the legs measuring instrument "
Word.create :word => "calumny", :definition => "slander aspersion "
Word.create :word => "candid", :definition => "frank straight-forward "
Word.create :word => "cant", :definition => "insincere talk/jargon "
Word.create :word => "cantankerous", :definition => "bad-tempered/quarrelsome "
Word.create :word => "canvass", :definition => "discuss thoroughly sort of touting "
Word.create :word => "castigate", :definition => "to chastise correct by punishing "
Word.create :word => "castigation", :definition => "severe punishment "
Word.create :word => "catalyst", :definition => "substance that causes speeding up "
Word.create :word => "caustic", :definition => "biting sarcastic "
Word.create :word => "censure", :definition => "expression of blame or disapproval a rebuke "
Word.create :word => "centurion", :definition => "leader of a unit of 100 soldiers "
Word.create :word => "chary", :definition => "cautious wary "
Word.create :word => "chastened", :definition => "corrected punished "
Word.create :word => "chastisement", :definition => "punishment "
Word.create :word => "chauvinist", :definition => "a blindly devoted patriot "
Word.create :word => "chicanery", :definition => "legal trickery/false argument "
Word.create :word => "chisel", :definition => "steel tool for shaping materials "
Word.create :word => "churl", :definition => "bad-tempered person "
Word.create :word => "clamor", :definition => "shout complain with a lot of noise "
Word.create :word => "clientele", :definition => "customers "
Word.create :word => "clinch", :definition => "come to grips/settle conclusively "
Word.create :word => "cling", :definition => "to resist separation "
Word.create :word => "clot", :definition => "half-solid lump formed from liquid "
Word.create :word => "cloture", :definition => "closing device (in Parliament) to end a debate by voting "
Word.create :word => "coagulation", :definition => "change to a thick and solid state "
Word.create :word => "coalescing", :definition => "coming together and uniting into one substance "
Word.create :word => "coax", :definition => "get smb to do something by kindness "
Word.create :word => "coda", :definition => "passage that completes a piece of music "
Word.create :word => "coddle", :definition => "treat with care and tenderness "
Word.create :word => "coerce", :definition => "compel to force to make obedient "
Word.create :word => "coeval", :definition => "of the same period coexisting "
Word.create :word => "cogent", :definition => "strong convincing "
Word.create :word => "cogitate", :definition => "think deeply mediate "
Word.create :word => "cognizant", :definition => "being fully aware of "
Word.create :word => " cohort", :definition => "a group or band of people"
Word.create :word => "colander", :definition => "bowl-shaped vessel with many holes used to drain off water "
Word.create :word => "collusion", :definition => "secret agreement for a deceitful purpose "
Word.create :word => "combustion", :definition => "process of burning "
Word.create :word => "commemorate", :definition => "keep the memory of "
Word.create :word => "commodious", :definition => "having plenty of space for what is needed "
Word.create :word => "commuter", :definition => "person who travels regularly "
Word.create :word => "complaisance", :definition => "tending to comply obliging willingness to please "
Word.create :word => "compunction", :definition => "feeling of regret for one's action "
Word.create :word => "conceal", :definition => "hide keep secret "
Word.create :word => "conceit", :definition => "over-high opinion of too much pride "
Word.create :word => "conciliatory", :definition => "reconciling soothing comforting mollifying "
Word.create :word => "concord", :definition => "agreement or harmony "
Word.create :word => "concur", :definition => "agree in opinion happen together "
Word.create :word => "condense", :definition => "increase in density strength make laconic "
Word.create :word => " Conduce", :definition => " To bring about"
Word.create :word => "condone", :definition => "forgive "
Word.create :word => "congeal", :definition => "make or become stiff and solid "
Word.create :word => "conjoin", :definition => "to join together "
Word.create :word => "connoisseur", :definition => " a person with good judgement (e.g.. in art) "
Word.create :word => "connotation", :definition => "suggestion in addition to "
Word.create :word => "consequential", :definition => "pompous self important "
Word.create :word => "console", :definition => "give comfort or sympathy to "
Word.create :word => "conspicuous", :definition => "easily seen remarkable "
Word.create :word => "consternation", :definition => "surprise and fear dismay "
Word.create :word => "constrain", :definition => "compel "
Word.create :word => "constrict", :definition => "make tight or smaller "
Word.create :word => "consume", :definition => "get to the end of "
Word.create :word => "consummate", :definition => "perfect/make perfect/complete "
Word.create :word => "contemn", :definition => "to scorn or despise "
Word.create :word => "contentious", :definition => "argumentative pugnacious combative quarrelsome "
Word.create :word => "contiguous", :definition => "touching neighboring near "
Word.create :word => "contrite", :definition => "filled with deep sorrow for wrongdoing "
Word.create :word => "contumacious", :definition => "insubordinate rebellious "
Word.create :word => "conundrum", :definition => "a riddle dilemma enigma "
Word.create :word => "conviction", :definition => "convincing firm belief "
Word.create :word => "convoke", :definition => "call together summon "
Word.create :word => "convoluted", :definition => "complicated coiled twisted "
Word.create :word => "cordial", :definition => "warm and sincere "
Word.create :word => "cordon", :definition => "line (of police acting as a guard) "
Word.create :word => "cornucopia", :definition => "abundant supply "
Word.create :word => "corporeal", :definition => "physical of or for the body "
Word.create :word => "correlate", :definition => "have a mutual relation "
Word.create :word => "corroboration", :definition => "additional strengthening evidence "
Word.create :word => "countenance", :definition => "to favor or approve of "
Word.create :word => "counterfeit", :definition => "forgery "
Word.create :word => "countervail", :definition => "counterbalance "
Word.create :word => "covert", :definition => "disguised "
Word.create :word => "covetous", :definition => "eagerly desirous "
Word.create :word => "cower", :definition => "crouch shrink back "
Word.create :word => "coy", :definition => "shy/modest (esp of a girl) "
Word.create :word => "crass", :definition => "very great (es. stupidity) "
Word.create :word => "cravat", :definition => "piece of linen worn as a necktie "
Word.create :word => "craven", :definition => "cowardly "
Word.create :word => "crease", :definition => "line made by crushing white line on the ground in cricket "
Word.create :word => "credulity", :definition => "too great a readiness to believe things "
Word.create :word => "credulous", :definition => "ready to believe things "
Word.create :word => "crush", :definition => "press lose shape subdue overwhelm "
Word.create :word => "cryptic", :definition => "secret with a hidden meaning "
Word.create :word => "cumbersome", :definition => "burdensome heavy and awkward to carry "
Word.create :word => "curmudgeon", :definition => "bad-tempered person "
Word.create :word => "curriculum", :definition => "course of study "
Word.create :word => "cursory", :definition => "quick hurried "
Word.create :word => "curtail", :definition => "make shorter then was planned "
Word.create :word => "dainty", :definition => "pretty/delicate(food)/difficult to please "
Word.create :word => "daunt", :definition => "intimidate make fearful "
Word.create :word => "dawdler", :definition => "person who is slow waste of time "
Word.create :word => "dearth", :definition => "shortage "
Word.create :word => "debacle", :definition => "a breakup overthrow sudden disaster "
Word.create :word => "decorum", :definition => "propriety properness "
Word.create :word => "decree", :definition => "order given by authority "
Word.create :word => "decry", :definition => "disapprove of "
Word.create :word => "defer", :definition => "postpone give way (to show respect) "
Word.create :word => "deferential", :definition => "showing respect "
Word.create :word => "defiance", :definition => "open disobedience or resistance "
Word.create :word => "delineate", :definition => "to portray depict sketch out "
Word.create :word => "deluge", :definition => "great flood heavy rush of water "
Word.create :word => "demagogue", :definition => "person appealing not to reasons "
Word.create :word => "demur", :definition => "to hesitate raise objections "
Word.create :word => "denigrate", :definition => "blacken belittle sully defame "
Word.create :word => "denouement", :definition => "an outcome or solution the unraveling of a plot "
Word.create :word => "deplete", :definition => "use until none remains "
Word.create :word => "deposition", :definition => "dethronement depositing "
Word.create :word => "deprave", :definition => "make morally bad corrupt "
Word.create :word => "deprecate", :definition => "protest against express disapproval of "
Word.create :word => "dereliction", :definition => "deserting and leaving to fall into ruins "
Word.create :word => "derision", :definition => "ridicule mockery deriding "
Word.create :word => "derivative", :definition => "unoriginal obtained from another source "
Word.create :word => "derogatory", :definition => "insulting tending to damage "
Word.create :word => "descry", :definition => "catch sight of see something in the distance "
Word.create :word => "desiccant", :definition => "substance used to absorb moisture "
Word.create :word => "desuetude", :definition => "cessation of use disuse "
Word.create :word => "desultory", :definition => "aimless haphazard digressing at random "
Word.create :word => "deter", :definition => "discourage hinder "
Word.create :word => "detraction", :definition => "slandering verbal attack aspersion "
Word.create :word => "detumescence", :definition => "diminishing or lessening of swelling "
Word.create :word => "deviance", :definition => "being different in moral standards (from normal) "
Word.create :word => "dexterity", :definition => "skill (esp. in handling) "
Word.create :word => "diaphanous", :definition => "transparent gauzy "
Word.create :word => "diatribe", :definition => "bitter and violent attack in words "
Word.create :word => " didactic", :definition => "intended to instruct"
Word.create :word => "diffidence", :definition => "shyness "
Word.create :word => "dilate", :definition => "speak comprehensively become wider large "
Word.create :word => "disallow", :definition => "refuse to allow or accept as a correct "
Word.create :word => "discern", :definition => "see with an effort but clearly "
Word.create :word => "discomfit", :definition => "confuse embarrass "
Word.create :word => "disconcert", :definition => "upset the self-possession of "
Word.create :word => "discountenance", :definition => "refuse to approve of "
Word.create :word => "discourse", :definition => "speech lecture "
Word.create :word => "discredit", :definition => "refuse to believe "
Word.create :word => "discreet", :definition => "careful/prudent "
Word.create :word => "discrete", :definition => "individually distinct "
Word.create :word => "disdain", :definition => "look on with contempt "
Word.create :word => "disencumber", :definition => "free from encumbrance "
Word.create :word => "disheveled", :definition => "untidy "
Word.create :word => "disingenuous", :definition => "sophisticated artful trying to deceive cunning "
Word.create :word => "disinter", :definition => "dig up from the earth "
Word.create :word => "dislodge", :definition => "move force from the place occupied "
Word.create :word => "dismal", :definition => "sad gloomy miserable "
Word.create :word => "disparate", :definition => "essentially different "
Word.create :word => "disproof", :definition => "proof to the contrary "
Word.create :word => "dissemble", :definition => "speak or behave so as to hide something (in mind) "
Word.create :word => "disseminate", :definition => "distribute (esp. ideas) "
Word.create :word => "dissent", :definition => "have a different opinion refuse to assent "
Word.create :word => "dissolution", :definition => "disintegration looseness in morals "
Word.create :word => "distraught", :definition => "distracted violently upset in mind "
Word.create :word => "divergence", :definition => "getting farther apart from a point "
Word.create :word => "divestiture", :definition => "taking off getting rid of giving up "
Word.create :word => "divulge", :definition => "make known something secret "
Word.create :word => "doggerel", :definition => "trivial poorly constructed verse "
Word.create :word => "dogmatic", :definition => "positive certain arbitrary without room for discussion "
Word.create :word => "dolt", :definition => "stupid fellow "
Word.create :word => "dormant", :definition => "in a state of inactivity but awaiting development "
Word.create :word => "dote", :definition => "show much fondness center one's attention "
Word.create :word => "drawl", :definition => "slow way of speaking "
Word.create :word => "droll", :definition => "jesting "
Word.create :word => "drone", :definition => "male bee person who isn't self-employed "
Word.create :word => "drowsiness", :definition => "feeling sleepy half asleep "
Word.create :word => "dubious", :definition => "feeling doubt "
Word.create :word => "dud", :definition => "no use person something that fails "
Word.create :word => "dulcet", :definition => "melodious harmonious "
Word.create :word => "dupe", :definition => "cheat make a fool of "
Word.create :word => "duplicity", :definition => "deliberate deception "
Word.create :word => "duress", :definition => "threats to compel smb "
Word.create :word => "dwarf", :definition => "person or smb much below the usual size "
Word.create :word => "dynamo", :definition => "a generator something that produces electric current "
Word.create :word => "earthenware", :definition => "dishes made of baked clay "
Word.create :word => "ebullience", :definition => "exuberance outburst of feeling "
Word.create :word => "ebullient", :definition => "overflowing with enthusiasm showing excitement "
Word.create :word => "ecumenical", :definition => "representing the whole Christian world "
Word.create :word => "edacious", :definition => "voracious devouring "
Word.create :word => "eddy", :definition => "circular or spiral movement (e.g.. of wind) "
Word.create :word => "edible", :definition => "fit to be eaten/not poisonous "
Word.create :word => "effete", :definition => "infertile worn out weak "
Word.create :word => "efficacy", :definition => "production of a desired result "
Word.create :word => "effluvia", :definition => "outflow in a stream of particles a noxious odor or vapor "
Word.create :word => "effrontery", :definition => "boldness impudence arrogance "
Word.create :word => "egress", :definition => "way out exit "
Word.create :word => "elaborate", :definition => "worked out with much care in great detail "
Word.create :word => "elegy", :definition => "a lament a melancholy composition "
Word.create :word => "elicit", :definition => "draw out "
Word.create :word => "eloquence", :definition => "fluent speaking skillful use of language "
Word.create :word => "emaciate", :definition => "make thin and weak "
Word.create :word => "embellish", :definition => "make beautiful "
Word.create :word => "embezzle", :definition => "use in a wrong way for one's own benefit "
Word.create :word => "emote", :definition => "stir up excite "
Word.create :word => "empirical", :definition => "relying on experiment "
Word.create :word => "encapsulate", :definition => "enclose in capsule "
Word.create :word => "encomium", :definition => "warm or glowing praise eulogy panegyric "
Word.create :word => "encumbrance", :definition => "burden things that get on the way of "
Word.create :word => "endearing", :definition => "making dear or liked "
Word.create :word => "endemic", :definition => "epidemic "
Word.create :word => "epiphany", :definition => " A Christian feast celebrating the manifestation of the divine nature of Jesus to the Gentiles as represented by the Magi."
Word.create :word => "endorse", :definition => "write one's name on the back of "
Word.create :word => "enduring", :definition => "lasting "
Word.create :word => "enervate", :definition => "weaken deprive of strength attenuate "
Word.create :word => "engender", :definition => "cause produce give rise to "
Word.create :word => "engrave", :definition => "impress deeply "
Word.create :word => "engrossing", :definition => "taken up all the time or attention writing in large or formal"
Word.create :word => "engulf", :definition => "swallow up "
Word.create :word => "enigma", :definition => " something that is puzzling "
Word.create :word => "enmity", :definition => "hatred being an enemy "
Word.create :word => "ensign", :definition => "flag/badge "
Word.create :word => "entangle", :definition => "put into difficulties "
Word.create :word => "enthral", :definition => "please greatly/enslave (fig) "
Word.create :word => "entice", :definition => "tempt or persuade "
Word.create :word => "entreat", :definition => "ask earnestly "
Word.create :word => "enunciate", :definition => "pronounce (words)/express a theory "
Word.create :word => "enzyme", :definition => "catalyst "
Word.create :word => "epicurean", :definition => "devoted to pleasure (sensuous enjoyment) "
Word.create :word => "epistle", :definition => "letter "
Word.create :word => "epithet", :definition => "adjective "
Word.create :word => "epitome", :definition => "brief summary representative example a typical model "
Word.create :word => "equable", :definition => "steady regular "
Word.create :word => "equanimity", :definition => "calmness of temperament "
Word.create :word => "equilibrium", :definition => "state of being balanced "
Word.create :word => "equipoise", :definition => "equal distribution of weight equilibrium "
Word.create :word => "equivocal", :definition => "having a double or doubtful meaning suspicious "
Word.create :word => "equivocate", :definition => "try to deceive by equivocal language "
Word.create :word => "eradicate", :definition => "get rid of pull up by the roots "
Word.create :word => "erratic", :definition => "irregular in behaviour or opinion "
Word.create :word => "erudite", :definition => "learned scholarly "
Word.create :word => "eschew", :definition => "avoid "
Word.create :word => "esoteric", :definition => "abstruse intended only for a small circle of "
Word.create :word => "espouse", :definition => "marry give one's support to "
Word.create :word => "eulogy", :definition => "formal praise panegyric "
Word.create :word => "euphoria", :definition => "elation state of pleasant excitement "
Word.create :word => "euthanasia", :definition => "easy and painless death "
Word.create :word => "evasive", :definition => "tending to evade "
Word.create :word => "evince", :definition => "to show clearly to indicate "
Word.create :word => "evoke", :definition => "call up bring out "
Word.create :word => "excoriation", :definition => "severe criticism "
Word.create :word => "exculpate", :definition => "to clear from a charge of guilt "
Word.create :word => "exhaustive", :definition => "complete thorough "
Word.create :word => "exigency", :definition => "emergency an urgent situation "
Word.create :word => "exoneration", :definition => "set smb clear free (e.g.. from blame) "
Word.create :word => "exorbitant", :definition => "much too high or great "
Word.create :word => "expatiate", :definition => "to roam wander freely "
Word.create :word => "expedient", :definition => "likely to be useful for a purpose "
Word.create :word => "expiation", :definition => "ending expiring "
Word.create :word => "exploit", :definition => "brilliant achievement develop use selfishly "
Word.create :word => "expostulate", :definition => "argue earnestly to dissuade correct or protest "
Word.create :word => "expurgate", :definition => "to remove obscenity purify censor "
Word.create :word => "exscind", :definition => "to cut out cut away "
Word.create :word => "extant", :definition => "still in existence "
Word.create :word => "extempore", :definition => "without previous thought or preparation "
Word.create :word => "extenuate", :definition => "reduce the strength of lessen seriousness partially excuse "
Word.create :word => "extinct", :definition => "no longer active "
Word.create :word => "extinguish", :definition => "end the existence of/wipe or put out "
Word.create :word => "extirpate", :definition => "to destroy exterminate cut out exscind "
Word.create :word => "extol", :definition => "praise highly "
Word.create :word => "extort", :definition => "obtain by threats violence "
Word.create :word => "extralegal", :definition => "outside the law "
Word.create :word => "extricable", :definition => "that can be freed "
Word.create :word => "extrovert", :definition => "cheerful person "
Word.create :word => "exuberance", :definition => "state of growing vigorously being full of life "
Word.create :word => "facetious", :definition => "humorous funny jocular "
Word.create :word => "facile", :definition => "easily done "
Word.create :word => " fagged", :definition => " too tired, exhausted"
Word.create :word => "fallacious", :definition => "based on error "
Word.create :word => "falter", :definition => "waver/move in an uncertain manner "
Word.create :word => "fatuous", :definition => "without sense foolish self-satisfaction "
Word.create :word => "fawn", :definition => "young deer try to win smb's favor "
Word.create :word => "feckless", :definition => "lacking purpose or vitality ineffective careless "
Word.create :word => "fecund", :definition => "fertile "
Word.create :word => "feint", :definition => "pretend "
Word.create :word => "felicitous", :definition => "apt suitably expressed well chosen apropos "
Word.create :word => "felon", :definition => "person guilty of murder "
Word.create :word => "ferment", :definition => "substance become excited "
Word.create :word => "ferocity", :definition => "savage cruelty "
Word.create :word => "ferret", :definition => "discover by searching search "
Word.create :word => "fervid", :definition => "showing earnest feeling "
Word.create :word => "fervor", :definition => "warmth of feelings earnestness "
Word.create :word => "fetid", :definition => "stinking "
Word.create :word => "fetter", :definition => "to shackle put in chains "
Word.create :word => "feud", :definition => "bitter quarrel over a long period of time "
Word.create :word => "fidelity", :definition => "loyalty accuracy "
Word.create :word => "fidget", :definition => "move restlessly make nervous "
Word.create :word => "figurehead", :definition => "carved image on the prow of a ship "
Word.create :word => "finesse", :definition => "delicate way of dealing with a situation "
Word.create :word => "finical", :definition => "too fussy about food clothing etc. "
Word.create :word => "finicky", :definition => "finical "
Word.create :word => "fission", :definition => "splitting or division (esp. of cells) "
Word.create :word => "fixate", :definition => "stare at "
Word.create :word => "flak", :definition => "criticism/anti-aircraft guns "
Word.create :word => "flamboyant", :definition => "brightly colored florid "
Word.create :word => "flaunting", :definition => "show off complacently "
Word.create :word => "flax", :definition => "pale yellow (hair) a plant "
Word.create :word => "fledged", :definition => "able to fly trained experienced "
Word.create :word => "fleet", :definition => "number of ships quick-moving "
Word.create :word => "flinch", :definition => "draw move back wince "
Word.create :word => "flop", :definition => "fail/move/fall clumsily "
Word.create :word => "florid", :definition => "very much ornamented naturally red (e.g.. of face) "
Word.create :word => "flout", :definition => "reject mock to go against (as in going against tradition) "
Word.create :word => "fluke", :definition => "lucky stroke "
Word.create :word => "fluster", :definition => "make nervous or confused "
Word.create :word => "foible", :definition => "defect of character (a person is wrongly proud) "
Word.create :word => "foil", :definition => "prevent from carrying out contrast "
Word.create :word => "foment", :definition => "put something warm (to lessen the pain) "
Word.create :word => "foolproof", :definition => "incapable of failure or error "
Word.create :word => "foppish", :definition => "like a man who pays too much attention to his clothes "
Word.create :word => "forage", :definition => "food for horses and cattle "
Word.create :word => "forbear", :definition => "refrain from be patient ancestor "
Word.create :word => "forbearance", :definition => "patience willingness to wait "
Word.create :word => "ford", :definition => "shallow place in a river (to cross) "
Word.create :word => "forestall", :definition => "prevent by taking action in advance preempt "
Word.create :word => "forfeit", :definition => "suffer the loss of something"
Word.create :word => "forge", :definition => "workshop for the shaping of metal to shape metal lead "
Word.create :word => "forgery", :definition => "counterfeit "
Word.create :word => "forswear", :definition => "renounce disallow repudiate "
Word.create :word => "foster", :definition => "nurture care for "
Word.create :word => "fracas", :definition => "noisy quarrel "
Word.create :word => "fragile", :definition => "easily injured broken or destroyed "
Word.create :word => "fragrant", :definition => "sweet-smelling "
Word.create :word => "frantic", :definition => "wildly excited with joy pain anxiety "
Word.create :word => "frenetic", :definition => "frantic frenzied "
Word.create :word => "fret", :definition => "worry irritation wear away "
Word.create :word => "fringe", :definition => "edge ornamental border part of hair over the forehead "
Word.create :word => "froward", :definition => "intractable not willing to yield or comply stubborn "
Word.create :word => "frugal", :definition => "careful economical "
Word.create :word => "fulmination", :definition => "bitter protest "
Word.create :word => "fulsome", :definition => "disgusting offensive due to excessiveness "
Word.create :word => "gainsay", :definition => "to deny to oppose"
Word.create :word => "garble", :definition => "make unfair selection from facts "
Word.create :word => "garner", :definition => "to gather and save to store up "
Word.create :word => "garrulity", :definition => "talkativeness "
Word.create :word => "garrulous", :definition => "too talkative "
Word.create :word => "gaucherie", :definition => "socially awkward tactless behavior "
Word.create :word => "germane", :definition => "relevant pertinent to "
Word.create :word => "gist", :definition => "the point general sense "
Word.create :word => "glean", :definition => "gather facts in small quantities "
Word.create :word => "glib", :definition => "ready and smooth but not sincere "
Word.create :word => "glimmer", :definition => "weak/unsteady light "
Word.create :word => "gloat", :definition => "over look at with selfish delight "
Word.create :word => "glut", :definition => "supply to much fill to excess "
Word.create :word => "gnaw", :definition => "waste away bite steadily "
Word.create :word => "goad", :definition => " something urging a person to action "
Word.create :word => "gorge", :definition => "eat greedily/narrow opening with a stream "
Word.create :word => "gossamer", :definition => "soft light delicate material "
Word.create :word => "gouge", :definition => "tool for cutting grooves in wood "
Word.create :word => " gourmand", :definition => " a person who is devoted to eating and drinking to excess "
Word.create :word => "grandiloquent", :definition => "using pompous words "
Word.create :word => "grave", :definition => "serious requiring consideration "
Word.create :word => "graze", :definition => "touch or scrape lightly in passing "
Word.create :word => "gregarious", :definition => "living in societies liking the company "
Word.create :word => "grievous", :definition => "causing grief or pain serious dire grave "
Word.create :word => "grovel", :definition => "crawl humble oneself "
Word.create :word => "guile", :definition => "deceit cunning "
Word.create :word => "gullible", :definition => "easily gulled "
Word.create :word => "gush", :definition => "burst out suddenly/talk ardently "
Word.create :word => "gust", :definition => "outburst of feeling sudden rain wind fire etc. "
Word.create :word => "hack", :definition => "cut roughly hired horse "
Word.create :word => "halcyon", :definition => "calm and peaceful "
Word.create :word => "hallow", :definition => "to make holy consecrate "
Word.create :word => "harangue", :definition => "a long passionate speech "
Word.create :word => "harbinger", :definition => " something or smb that foretells the coming of "
Word.create :word => "harrow", :definition => "to distress create stress or torment "
Word.create :word => "haughty", :definition => "arrogant conceited "
Word.create :word => "heed", :definition => "attention/give notice to "
Word.create :word => "heinous", :definition => "odious (of crime) "
Word.create :word => "heresy", :definition => "belief contrary to what is generally accepted "
Word.create :word => "hermetic", :definition => "sealed by fusion "
Word.create :word => "heterogeneous", :definition => "made up of different kinds "
Word.create :word => "hew", :definition => "make by hard work cut (by striking) "
Word.create :word => "highbrow", :definition => "(person) with superior tastes "
Word.create :word => "hirsute", :definition => "hairy shaggy "
Word.create :word => "hoax", :definition => "mischievous trick played on smb for a joke "
Word.create :word => "hoi", :definition => "polloi the masses the rabble "
Word.create :word => "hollow", :definition => "not soled with hole "
Word.create :word => "holster", :definition => "leather case for a pistol "
Word.create :word => "homiletics", :definition => "act of preaching "
Word.create :word => "hone", :definition => "stone used for sharpening tools "
Word.create :word => "hoodwink", :definition => "trick mislead "
Word.create :word => "hospitable", :definition => "liking to give hospitality "
Word.create :word => "hubris", :definition => "arrogant pride "
Word.create :word => "hush", :definition => "make or become silent "
Word.create :word => "husk", :definition => "worthless outside part of anything "
Word.create :word => "hypocrisy", :definition => "falsely making oneself appear to be good "
Word.create :word => "iconoclast", :definition => "person who attacks popular beliefs "
Word.create :word => "idiosyncrasy", :definition => "personal mannerism "
Word.create :word => "idolatry", :definition => "excessive admiration of "
Word.create :word => "idyll", :definition => "a carefree episode or experience "
Word.create :word => "ignoble", :definition => "dishonorable common undignified "
Word.create :word => "ignominious", :definition => "shameful dishonorable undignified disgraceful "
Word.create :word => "illicit", :definition => "unlawful forbidden "
Word.create :word => "imbroglio", :definition => "complicated and embarrassing situation "
Word.create :word => "immaculate", :definition => "pure faultless "
Word.create :word => "imminent", :definition => "likely to come or happen soon "
Word.create :word => "immutable", :definition => "that cannot be changed "
Word.create :word => "impair", :definition => "worsen diminish in value "
Word.create :word => "impassive", :definition => "unmoved feeling no sign of passion "
Word.create :word => "impecunious", :definition => "having little or no money "
Word.create :word => "impede", :definition => "hinder get in the way of "
Word.create :word => "impediment", :definition => " something that hinders (e.g. stammer) "
Word.create :word => "impending", :definition => "imminent being about to happen expected "
Word.create :word => "imperative", :definition => "urgent essential "
Word.create :word => "imperious", :definition => "commanding haughty arrogant "
Word.create :word => "impermeable", :definition => "that cannot be permeated "
Word.create :word => "imperturbable", :definition => "calm not capable of being excited "
Word.create :word => "impervious", :definition => "not allowing to pass through (of materials) "
Word.create :word => "imperviousness", :definition => "haughty arrogant commanding "
Word.create :word => "impetuous", :definition => "having sudden energy impulsive thrusting ahead forceful "
Word.create :word => "impiety", :definition => "lack of reverence or dutifulness "
Word.create :word => "implacable", :definition => "incapable of being placated unpleasable "
Word.create :word => "implicate", :definition => "show that smb has a share "
Word.create :word => "implicit", :definition => "implied though not plainly expressed"
Word.create :word => "implosion", :definition => "collapse bursting inward "
Word.create :word => "importune", :definition => "beg urgently solicit (of a prostitute) "
Word.create :word => "imprecation", :definition => "an invocation of evil a curse "
Word.create :word => "impromptu", :definition => "without preparation "
Word.create :word => "impudent", :definition => "rash indiscreet "
Word.create :word => "impugned", :definition => "challenged to be doubted "
Word.create :word => "impute", :definition => "to attribute to a cause or source ascribe "
Word.create :word => "inadvertent", :definition => "not paying proper attention "
Word.create :word => "inane", :definition => "silly senseless "
Word.create :word => "inasmuch", :definition => "since because "
Word.create :word => "incense", :definition => "make angry "
Word.create :word => "incessant", :definition => "often repeated continual "
Word.create :word => "inchoate", :definition => "not yet fully formed rudimentary elementary "
Word.create :word => "incipient", :definition => "beginning "
Word.create :word => "incise", :definition => "engrave make a cut in "
Word.create :word => "incite", :definition => "stir up rouse "
Word.create :word => "inclined", :definition => "directing the mind in a certain direction "
Word.create :word => "incongruous", :definition => "out of place not in harmony or agreement "
Word.create :word => "incorrigibility", :definition => "cannot be cured or corrected "
Word.create :word => "incredulous", :definition => "skeptical unwilling to believe "
Word.create :word => "inculcate", :definition => "fix firmly by repetition "
Word.create :word => "incumbents", :definition => "official duties "
Word.create :word => "incursion", :definition => "a raid a sudden attack "
Word.create :word => "indefatigability", :definition => "not easily exhaustible tirelessness "
Word.create :word => "indelible", :definition => "that cannot be rubbed out "
Word.create :word => "indigence", :definition => "poverty "
Word.create :word => "indigenous", :definition => "native "
Word.create :word => "indistinct", :definition => "not easily heard seen clearly marked "
Word.create :word => "indolence", :definition => "laziness "
Word.create :word => "indomitable", :definition => "not easily discouraged or subdued "
Word.create :word => "indulge", :definition => "gratify give way to satisfy allow oneself "
Word.create :word => "indulgent", :definition => "inclined to indulge "
Word.create :word => "ineffable", :definition => "to great to be described in words "
Word.create :word => "ineluctable", :definition => "certain inevitable "
Word.create :word => "inept", :definition => "unskillful said or done at the wrong time "
Word.create :word => "ineptitude", :definition => "quality of being unskillful "
Word.create :word => "inferno", :definition => "hell "
Word.create :word => "infuriate", :definition => "fill with fury or rage "
Word.create :word => "infuse", :definition => "put pour fill "
Word.create :word => "ingenuous", :definition => "naive young artless frank honest sincere "
Word.create :word => "ingest", :definition => "take in by swallowing "
Word.create :word => "inimical", :definition => "harmful or friendly "
Word.create :word => "inimitable", :definition => "defying imitation unmatchable "
Word.create :word => "innocuous", :definition => "causing no harm "
Word.create :word => "inscrutable", :definition => "incapable of being discovered or understood "
Word.create :word => "insensible", :definition => "unconscious unresponsive unaffected "
Word.create :word => "insinuate", :definition => "suggest unpleasantly make a way for something gently "
Word.create :word => "insipid", :definition => "without taste or flavor "
Word.create :word => "insouciant", :definition => "unconcerned carefree "
Word.create :word => "insularity", :definition => "narrow-mindedness isolated "
Word.create :word => "insurrection", :definition => "rising of people to open resistance to "
Word.create :word => "interdict", :definition => "prohibit forbid "
Word.create :word => "interim", :definition => "as an installment "
Word.create :word => "intersperse", :definition => "place here and there "
Word.create :word => "intransigence", :definition => "unwillingness to compromise stubbornness intractability "
Word.create :word => "intransigent", :definition => "uncompromising "
Word.create :word => "intrepid", :definition => "fearless brave undaunted "
Word.create :word => "introspection", :definition => "examining one's own thoughts and feelings "
Word.create :word => "inundate", :definition => "flood cover by overflowing "
Word.create :word => "inured", :definition => "accustomed to adapted "
Word.create :word => "invective", :definition => "abusive language curses "
Word.create :word => "inveigh", :definition => "to attack verbally denounce deprecate "
Word.create :word => "inveterate", :definition => "deep-rooted. long-established "
Word.create :word => "invincible", :definition => "too strong to be defeated "
Word.create :word => "involute", :definition => "complex "
Word.create :word => "irascible", :definition => "irritable easily angered "
Word.create :word => "irate", :definition => "angry "
Word.create :word => "ire", :definition => "anger "
Word.create :word => "irksome", :definition => "tiresome "
Word.create :word => "irresolute", :definition => "hesitating undecided "
Word.create :word => "irrevocable", :definition => "final and unalterable "
Word.create :word => "itinerate", :definition => "to travel from place to place to peregrinate "
Word.create :word => "jabber", :definition => "talk excitedly utter rapidly "
Word.create :word => " jagged", :definition => " notched, rough"
Word.create :word => "jibe", :definition => "gibe make fun of "
Word.create :word => "jocular", :definition => "meant as a joke "
Word.create :word => "judicious", :definition => "sound in judgment wise "
Word.create :word => "knit", :definition => "draw together unite firmly "
Word.create :word => "labyrinthine", :definition => "to entangle the state of affairs "
Word.create :word => "lachrymose", :definition => "causing tears tearful "
Word.create :word => "lackluster", :definition => "(of eyes) dull "
Word.create :word => "lament", :definition => "show feel great sorrow "
Word.create :word => "lassitude", :definition => "weariness tiredness "
Word.create :word => "latent", :definition => "present but not yet active developed or visible "
Word.create :word => "laudatory", :definition => "expressing or giving praise "
Word.create :word => "lavish", :definition => "giving or producing freely liberally or generously "
Word.create :word => "legacy", :definition => " something handed down from ancestors "
Word.create :word => "levee", :definition => "formal reception/embankment "
Word.create :word => "levity", :definition => "lack of seriousness "
Word.create :word => "libel", :definition => "statement that damages reputation "
Word.create :word => "liberality", :definition => "free giving generosity "
Word.create :word => "libertine", :definition => "immoral person "
Word.create :word => "lien", :definition => "legal claim until a debt on it is repaid "
Word.create :word => "limn", :definition => "paint portray "
Word.create :word => "limp", :definition => "lacking strength walking unevenly "
Word.create :word => "lionize", :definition => "treat as a famous person "
Word.create :word => "lithe", :definition => "bending twisting "
Word.create :word => "loll", :definition => "rest to sit or stand in a lazy way hang (dog's tongue)"
Word.create :word => "lope", :definition => "move along with long strides "
Word.create :word => "loquacious", :definition => "talkative garrulous "
Word.create :word => "lucubrate", :definition => "write in scholarly fashion "
Word.create :word => "luculent", :definition => "easily understood lucid clear "
Word.create :word => "lugubrious", :definition => "mournful excessively sad "
Word.create :word => "lull", :definition => "become quiet or less active "
Word.create :word => "lumber", :definition => "move in a clumsy/noisy way "
Word.create :word => "luminary", :definition => "star light-giving body "
Word.create :word => "lurk", :definition => "be out of view ready to attack "
Word.create :word => "lustrous", :definition => "being bright polished "
Word.create :word => "macabre", :definition => "gruesome suggesting death "
Word.create :word => "macerate", :definition => "make or become soft by soaking in water "
Word.create :word => "machination", :definition => "plot scheme (esp. evil) "
Word.create :word => "maladroit", :definition => "tactless clumsy "
Word.create :word => "malapropism", :definition => "misuse of a word (for one that resembles it) "
Word.create :word => "malevolence", :definition => "wishing to do evil "
Word.create :word => "malign", :definition => "injurious speak ill of smb tell lie "
Word.create :word => "malinger", :definition => "to fake illness or injury in order to shirk a duty "
Word.create :word => "malleable", :definition => "yielding easily shaped moldable adapting "
Word.create :word => "manacle", :definition => "chains for the hands or feet "
Word.create :word => "massacre", :definition => "cruel killing of a large number of people "
Word.create :word => "matriculation", :definition => "be admitted enter a university as a student "
Word.create :word => "maudlin", :definition => "sentimental in a silly or tearful way "
Word.create :word => "maul", :definition => "hurt by rough handling "
Word.create :word => "maverick", :definition => "rebel nonconformist "
Word.create :word => "mellifluous", :definition => "sweetly flowing "
Word.create :word => "mendacity", :definition => "dishonesty "
Word.create :word => "mendicant", :definition => "a beggar "
Word.create :word => "mercurial", :definition => "quick changeable in character fleeting "
Word.create :word => "meretricious", :definition => "attractive on the surface but of little value "
Word.create :word => "mesmerize", :definition => "hypnotize "
Word.create :word => "meticulous", :definition => "giving great attention to details "
Word.create :word => "mettle", :definition => "quality of endurance or courage "
Word.create :word => "mettlesome", :definition => "courageous high-spirited "
Word.create :word => "middling", :definition => "fairly good but not very good "
Word.create :word => "minatory", :definition => "menacing threatening "
Word.create :word => "mince", :definition => "pronounce or speak affectedly euphemize "
Word.create :word => "misanthrope", :definition => "person who hates mankind "
Word.create :word => "mischievous", :definition => "harmful causing mischief "
Word.create :word => "miser", :definition => "person who loves wealth and spends little "
Word.create :word => "misogynist", :definition => "one who hates women/females "
Word.create :word => " mite", :definition => " Avery small amount, portion, or particle"
Word.create :word => "moderation", :definition => "quality of being limited not extreme "
Word.create :word => "mollify", :definition => "make calmer or quieter "
Word.create :word => "molt", :definition => "moult lose hair feathers before new growing "
Word.create :word => "morbid", :definition => "diseased unhealthy (e.g.. about ideas) "
Word.create :word => "morose", :definition => "ill-tempered unsocial "
Word.create :word => "muffler", :definition => "cloth worn round the neck/silencer "
Word.create :word => "multifarious", :definition => "varied motley greatly diversified "
Word.create :word => "mundane", :definition => "worldly as opposed to spiritual commonplace everyday "
Word.create :word => "myriad", :definition => "very great number "
Word.create :word => "nadir", :definition => "lowest weakest point "
Word.create :word => "nascent", :definition => "coming into existence emerging "
Word.create :word => "nebulous", :definition => "cloud-like hazy vague indistinct "
Word.create :word => "negligent", :definition => "taking too little care "
Word.create :word => "neophyte", :definition => "person who has been converted to a belief "
Word.create :word => "nexus", :definition => "a connection tie or link "
Word.create :word => "nibble", :definition => "show some inclination to accept (an offer) "
Word.create :word => "noisome", :definition => "offensive disgusting (smell) "
Word.create :word => "nonchalant", :definition => "not having interest "
Word.create :word => "nonplused", :definition => "greatly surprised "
Word.create :word => "nostrum", :definition => "a quack remedy an untested cure "
Word.create :word => "noxious", :definition => "harmful "
Word.create :word => "nugatory", :definition => "trifling/worthless "
Word.create :word => "obdurate", :definition => "hardened and unrepenting stubborn inflexible "
Word.create :word => "obfuscate", :definition => "to darken make obscure muddle "
Word.create :word => "oblivious", :definition => "unaware having no memory "
Word.create :word => "obloquy", :definition => "abusively detractive language sharp criticism vituperation "
Word.create :word => "obsequious", :definition => "too eager to obey or serve "
Word.create :word => "obstreperous", :definition => "noisy loud "
Word.create :word => "obtain", :definition => "to be established accepted or customary "
Word.create :word => "obtrusive", :definition => "projecting prominent undesirably noticeable "
Word.create :word => "obtuse", :definition => "blunt/stupid "
Word.create :word => "obviate", :definition => "to make unnecessary get rid of "
Word.create :word => "occluded", :definition => "blocked up "
Word.create :word => "odious", :definition => "repulsive hateful "
Word.create :word => "odium", :definition => "contempt dislike aversion "
Word.create :word => "odor", :definition => "smell favor reputation "
Word.create :word => "officious", :definition => "too eager or ready to help offer advice "
Word.create :word => "ominous", :definition => "threatening "
Word.create :word => "onerous", :definition => "needing effort burdensome "
Word.create :word => "opaqueness", :definition => "dullness/not allowing light to pass through "
Word.create :word => "opprobrious", :definition => "showing scorn or reproach "
Word.create :word => "ossify", :definition => "to turn to bone to settle rigidly into an idea "
Word.create :word => "ostensible", :definition => "seeming appearing as such professed "
Word.create :word => "ostentation", :definition => "display to obtain admiration or envy "
Word.create :word => "ostracism", :definition => "shut out from society refuse to meet talk "
Word.create :word => "overhaul", :definition => "examine thoroughly to learn about the condition "
Word.create :word => "overweening", :definition => "presumptuously arrogant overbearing immoderate being a jerk "
Word.create :word => "paean", :definition => "song of praise or triumph "
Word.create :word => "palate", :definition => "roof of the mouth sense of taste "
Word.create :word => "palatial", :definition => "magnificent "
Word.create :word => "palliate", :definition => "lessen the severity of "
Word.create :word => "palpability", :definition => "can be felt touched understood "
Word.create :word => "palpitate", :definition => "tremble beat rapidly and irregularly "
Word.create :word => "panegyric", :definition => "formal praise eulogy "
Word.create :word => "paradigm", :definition => "a model example or pattern "
Word.create :word => "parenthesis", :definition => "sentence within another one something separated "
Word.create :word => "pariah", :definition => "an outcast a rejected and despised person "
Word.create :word => " parley", :definition => " negotiation, discussion between enemies"
Word.create :word => "parsimonious", :definition => "too economical miserly "
Word.create :word => "partisan", :definition => "one-sided committed to a party biased or prejudiced "
Word.create :word => "patron", :definition => "regular customer person who gives support "
Word.create :word => "paucity", :definition => "scarcity a lacking of "
Word.create :word => "peccadillo", :definition => "small sin small weakness in one's character "
Word.create :word => "pedantic", :definition => "bookish showing off learning "
Word.create :word => "pedestrian", :definition => "commonplace trite unremarkable "
Word.create :word => "pellucid", :definition => "transparent easy to understand "
Word.create :word => "penchant", :definition => "strong inclination a liking "
Word.create :word => "penitent", :definition => "feeling or showing regret "
Word.create :word => "penurious", :definition => "poor/stingy "
Word.create :word => "penury", :definition => "extreme poverty "
Word.create :word => "peregrination", :definition => "traveling about wandering "
Word.create :word => "peremptory", :definition => "urgent imperative unchallengeable ending debate "
Word.create :word => "perfidious", :definition => "treacherous faithless "
Word.create :word => "perfidy", :definition => "treachery breaking of faith "
Word.create :word => "perfunctory", :definition => "done as a duty without care "
Word.create :word => "perilous", :definition => "dangerous "
Word.create :word => "peripatetic", :definition => "wandering "
Word.create :word => "perish", :definition => "be destroyed decay "
Word.create :word => "perjury", :definition => "willful FALSE statement unlawful act "
Word.create :word => "permeate", :definition => "spread into every part of "
Word.create :word => "pernicious", :definition => "harmful injurious "
Word.create :word => "perpetrate", :definition => "be guilty commit (a crime) "
Word.create :word => "personable", :definition => "pleasing in appearance attractive "
Word.create :word => "perspicacity", :definition => "quick judging and understanding "
Word.create :word => "pertain", :definition => "belong as a part have reference "
Word.create :word => "pest", :definition => "destructive thing or a person who is nuisance "
Word.create :word => "petrified", :definition => "taken away power (to think feel act) "
Word.create :word => "petrify", :definition => "to make hard rocklike "
Word.create :word => "petrous", :definition => "like a rock hard stony "
Word.create :word => "petulant", :definition => "unreasonably impatient "
Word.create :word => "philistine", :definition => "a smug ignorant person one who lacks knowledge "
Word.create :word => "phlegmatic", :definition => "calm sluggish temperament unemotional "
Word.create :word => "picaresque", :definition => "involving clever rogues or adventurers "
Word.create :word => "pied", :definition => "of mixed colors "
Word.create :word => "pinch", :definition => "be too tight take between the thumb and finger "
Word.create :word => "pine", :definition => "waste away through sorrow or illness "
Word.create :word => "pious", :definition => "dutiful to parents devoted to religion "
Word.create :word => "piquant", :definition => "agreeably pungent stimulating "
Word.create :word => "pique", :definition => "hurt the pride or self-respect stir (curiosity) "
Word.create :word => "pitfall", :definition => "covered hole as a trap unsuspected danger "
Word.create :word => "pith", :definition => "essential part force soft liquid substance "
Word.create :word => "pivotal", :definition => "of great importance (others depend on it) "
Word.create :word => "placate", :definition => "soothe pacify calm "
Word.create :word => "plaintive", :definition => "mournful melancholy sorrowful "
Word.create :word => "plaque", :definition => "flat metal on a wall as a memorial "
Word.create :word => "platitude", :definition => "a trite or banal statement unoriginality "
Word.create :word => "plea", :definition => "request "
Word.create :word => "plead", :definition => "address a court of law as an advocate "
Word.create :word => "plethora", :definition => "glut "
Word.create :word => "pliant", :definition => "pliable easily bent shaped or twisted "
Word.create :word => "plod", :definition => "continue doing something without resting "
Word.create :word => "pluck", :definition => "pull the feathers off pick (e.g.. flowers) "
Word.create :word => "plumb", :definition => "get to the root of "
Word.create :word => "plummet", :definition => "fall plunge steeply "
Word.create :word => "plunge", :definition => "move quickly suddenly and with force "
Word.create :word => "poignant", :definition => "deeply moving keen "
Word.create :word => "poncho", :definition => "large piece of cloth "
Word.create :word => "ponderous", :definition => "heavy bulky dull "
Word.create :word => "portent", :definition => "omen marvelous threatening "
Word.create :word => "precarious", :definition => "uncertain risky dangerous "
Word.create :word => "precepts", :definition => "rules establishing standards of conduct "
Word.create :word => "preclude", :definition => "prevent make impossible "
Word.create :word => "precursory", :definition => "preliminary anticipating "
Word.create :word => "predilection", :definition => "special liking mental preference "
Word.create :word => "predominate", :definition => "have more power than others "
Word.create :word => "preen", :definition => "tidy/show self-satisfaction "
Word.create :word => "premature", :definition => "doing or happening something before the right time "
Word.create :word => "preponderance", :definition => "greatness in number strength weight "
Word.create :word => "presage", :definition => "warning sign "
Word.create :word => "presumption", :definition => "arrogance "
Word.create :word => "preternatural", :definition => "not normal or usual "
Word.create :word => "prevalent", :definition => "common "
Word.create :word => "prevaricate", :definition => "to equivocate to stray from the truth "
Word.create :word => "prim", :definition => "neat formal "
Word.create :word => "pristine", :definition => "primitive unspoiled pure as in earlier times unadulterated "
Word.create :word => "probity", :definition => "uprightness incorruptibility principle "
Word.create :word => "proclivity", :definition => "inclination "
Word.create :word => "procrastination", :definition => "keeping on putting off "
Word.create :word => "prodigal", :definition => "wasteful reckless with money "
Word.create :word => "prodigious", :definition => "enormous wonderful "
Word.create :word => "profane", :definition => "worldly having contempt for God "
Word.create :word => "profligacy", :definition => "shameless immorality "
Word.create :word => "profligate", :definition => "wasteful prodigal licentious extravagant "
Word.create :word => "profundity", :definition => "depth "
Word.create :word => "profuse", :definition => "abundant/lavish "
Word.create :word => "proliferate", :definition => "grow reproduce by rapid multification "
Word.create :word => "prolix", :definition => "tiring because too long "
Word.create :word => "prone", :definition => "prostrate inclined to (undesirable things) "
Word.create :word => "propagation", :definition => "increasing the number spreading extending "
Word.create :word => "propinquity", :definition => "nearness in time or place affinity of nature "
Word.create :word => "propitiatory", :definition => "conciliatory appeasing mitigating "
Word.create :word => "propitious", :definition => "auspicious presenting favorable circumstances "
Word.create :word => "prosaic", :definition => "everyday mundane commonplace trite pedestrian "
Word.create :word => "proscribe", :definition => "denounce as dangerous "
Word.create :word => "protracted", :definition => "prolonged "
Word.create :word => "provident", :definition => "frugal looking to the future "
Word.create :word => "provisional", :definition => "of the present time only "
Word.create :word => "provoke", :definition => "make angry vax "
Word.create :word => "prudence", :definition => "careful forethought "
Word.create :word => "prudish", :definition => "easily shocked excessively modest "
Word.create :word => "prune", :definition => "dried plum silly person "
Word.create :word => "pry", :definition => "get something inquire too curiously "
Word.create :word => "pucker", :definition => "wrinkle "
Word.create :word => "pugnacious", :definition => "fond of in the habit of fighting "
Word.create :word => "puissance", :definition => "strength "
Word.create :word => "punctilious", :definition => "precise paying attention to trivialities "
Word.create :word => "pundit", :definition => "pedant authority on a subject "
Word.create :word => "pungency", :definition => "sharpness stinging quality "
Word.create :word => "purvey", :definition => "provide supply "
Word.create :word => "pusillanimous", :definition => "cowardly craven "
Word.create :word => "putrefaction", :definition => "becoming rotten "
Word.create :word => "pyre", :definition => "large pile of wood for burning "
Word.create :word => "quack", :definition => "person dishonestly claiming to something"
Word.create :word => "quaff", :definition => "drink deeply "
Word.create :word => "quail", :definition => "lose courage turn frightened "
Word.create :word => "qualm", :definition => "feeling of doubt temporary feeling of sickness "
Word.create :word => "quandary", :definition => "state of doubt or perplexity "
Word.create :word => "quell", :definition => "suppress subdue "
Word.create :word => "quibble", :definition => "try to avoid by sophistication "
Word.create :word => "quiescence", :definition => "state of being passive/motionless "
Word.create :word => "quiescent", :definition => "at rest dormant torpid "
Word.create :word => "quirk", :definition => "habit or action peculiar to smb or something"
Word.create :word => "quixotic", :definition => "generous unselfish "
Word.create :word => "quotidian", :definition => "banal everyday "
Word.create :word => "rabble", :definition => "mob crowd the lower classes of populace "
Word.create :word => "raconteur", :definition => "person who tells anecdotes "
Word.create :word => "raffish", :definition => "low vulgar base tawdry "
Word.create :word => "ramify", :definition => "to be divided or subdivided to branch out "
Word.create :word => "rancorous", :definition => "feeling bitterness spitefulness "
Word.create :word => "rant", :definition => "use extravagant language "
Word.create :word => "rapacious", :definition => "greedy (esp for money) "
Word.create :word => "rarefy", :definition => "to make thin to make less dense to purify or refine "
Word.create :word => "rave", :definition => "act with excessive enthusiasm "
Word.create :word => "reactionary", :definition => "opposing progress "
Word.create :word => "rebuff", :definition => "snub "
Word.create :word => "recalcitrant", :definition => "disobedient "
Word.create :word => "recant", :definition => "take back as being FALSE give up "
Word.create :word => "recast", :definition => "cast or fashion anew "
Word.create :word => "recidivism", :definition => "relapse into antisocial or criminal behavior "
Word.create :word => "reciprocity", :definition => "granting of privileges in return for similar "
Word.create :word => "recitals", :definition => "a number of performance of music "
Word.create :word => "recluse", :definition => "person who lives alone and avoids people "
Word.create :word => "recompense", :definition => "make payment to reward punish "
Word.create :word => "reconcile", :definition => "settle a quarrel restore peace "
Word.create :word => "recondite", :definition => "little known abstruse "
Word.create :word => "recreancy", :definition => "cowardice a cowardly giving up "
Word.create :word => "recuperate", :definition => "become strong after illness loss exhaustion "
Word.create :word => "redeem", :definition => "get back by payment compensate "
Word.create :word => "redoubtable", :definition => "formidable causing fear "
Word.create :word => "refine", :definition => "make or become pure cultural "
Word.create :word => "refractory", :definition => "stubborn unmanageable untractable "
Word.create :word => "refulgent", :definition => "shining brilliant "
Word.create :word => "regale", :definition => "to delight or entertain to feast "
Word.create :word => "regicide", :definition => "crime of killing a king"
Word.create :word => "reiterate", :definition => "say or do again several times "
Word.create :word => "rejuvenation", :definition => "becoming young in nature or appearance "
Word.create :word => "relapse", :definition => "fall back again "
Word.create :word => " reminiscent", :definition => " viewing the past"
Word.create :word => "remonstrate", :definition => "to protest object "
Word.create :word => "render", :definition => "deliver provide represent "
Word.create :word => "renovate", :definition => "restore something to better condition "
Word.create :word => "renowned", :definition => "celebrated famous "
Word.create :word => "repast", :definition => "meal "
Word.create :word => "repel", :definition => "refuse to accept/cause dislike "
Word.create :word => "repine", :definition => "at be discontented with "
Word.create :word => "reproach", :definition => "scold upbraid "
Word.create :word => "reprobate", :definition => "person hardened in sin one devoid of decency "
Word.create :word => "repudiate", :definition => "disown refuse to accept or pay "
Word.create :word => "repulsive", :definition => "causing a feeling of disgust "
Word.create :word => "requite", :definition => "repay give in return "
Word.create :word => "rescind", :definition => "repeal/annul/cancel "
Word.create :word => "resigned", :definition => "unresisting submissive "
Word.create :word => "resilience", :definition => "quality of quickly recovering the original shape "
Word.create :word => "resort", :definition => "to frequently visit "
Word.create :word => "restive", :definition => "refusing to move reluctant to be controlled "
Word.create :word => "resuscitation", :definition => "coming back to consciousness "
Word.create :word => "retard", :definition => "check hinder "
Word.create :word => "reticent", :definition => "reserved untalkative silent taciturn "
Word.create :word => " retrospective", :definition => " Looking back on past"
Word.create :word => "revere", :definition => "have deep respect for "
Word.create :word => "reverent", :definition => "feeling or showing deep respect "
Word.create :word => "riddle", :definition => "puzzling person or thing "
Word.create :word => "rift", :definition => "split crack dissension "
Word.create :word => "rivet", :definition => "fix take up secure metal pin "
Word.create :word => "roll", :definition => "call calling of names "
Word.create :word => "rotund", :definition => "rich and deep plump and round "
Word.create :word => "ruffian", :definition => "violent cruel man "
Word.create :word => "rumple", :definition => "make rough "
Word.create :word => "sagacious", :definition => "having sound judgment perceptive wise like a sage "
Word.create :word => "salacious", :definition => "obscene "
Word.create :word => "salubrious", :definition => "healthful "
Word.create :word => "salutary", :definition => "remedial wholesome causing improvement "
Word.create :word => "sanctimony", :definition => "self-righteousness hypocritical with FALSE piety "
Word.create :word => "sanction", :definition => "approval (by authority) penalty "
Word.create :word => "sanguine", :definition => "cheerful confident optimistic "
Word.create :word => "sanity", :definition => "health of mind soundness of judgment "
Word.create :word => "sash", :definition => "long strip worn round the waist "
Word.create :word => "satiate", :definition => "satisfy fully "
Word.create :word => "saturnine", :definition => "gloomy dark sullen morose "
Word.create :word => "savant", :definition => "person of great learning "
Word.create :word => "savor", :definition => "taste flavor something"
Word.create :word => "sawdust", :definition => "tiny bits of wood "
Word.create :word => "scabbard", :definition => "sheath for the blade "
Word.create :word => "scent", :definition => "smell (especially pleasant) "
Word.create :word => "scorch", :definition => "become discolored/dry up/go at high speed "
Word.create :word => "scribble", :definition => "write hastily "
Word.create :word => "scurvy", :definition => "mean contemptible "
Word.create :word => "secular", :definition => "material (not spiritual) living outside monasteries "
Word.create :word => "sedulous", :definition => "persevering "
Word.create :word => "seminal", :definition => "like a seed constituting a source originative "
Word.create :word => "sententious", :definition => "short and pithy full of maxims/proverbs "
Word.create :word => "sequence", :definition => "succession connected line of "
Word.create :word => "sere", :definition => "make hard and without feeling "
Word.create :word => "sermon", :definition => "reproving a person for his faults "
Word.create :word => "serrated", :definition => "having a toothed edge "
Word.create :word => "serration", :definition => "having a toothed edge "
Word.create :word => "servile", :definition => "like a slave lacking independence "
Word.create :word => "sever", :definition => "break off "
Word.create :word => "severance", :definition => "severing "
Word.create :word => "shallow", :definition => "little depth not earnest "
Word.create :word => "shard", :definition => "piece of broken earthenware "
Word.create :word => "sheath", :definition => "cover for the blade of a weapon or a tool "
Word.create :word => "shrewd", :definition => "astute showing sound judgement "
Word.create :word => "shrill", :definition => "sharp piercing "
Word.create :word => "shun", :definition => "keep away from avoid "
Word.create :word => "shunt", :definition => "send from one track to another lay aside evade discussion "
Word.create :word => "sidestep", :definition => "step to one side "
Word.create :word => "simper", :definition => "(give a) silly/self-conscious smile "
Word.create :word => "sinuous", :definition => "winding undulating serpentine "
Word.create :word => "skiff", :definition => "small boat "
Word.create :word => "skit", :definition => "short piece of humorous writing "
Word.create :word => "slack", :definition => "sluggish dull not tight "
Word.create :word => "slake", :definition => "to assuage to satisfy allay "
Word.create :word => "slate", :definition => "king of blue-grey stone propose criticize "
Word.create :word => "sluggard", :definition => "lazy slow-moving person "
Word.create :word => "slur", :definition => "join sounds/words (indistinct) "
Word.create :word => "smolder", :definition => "burn slowly without flame "
Word.create :word => "snare", :definition => "trap "
Word.create :word => "snub", :definition => "treat with contempt "
Word.create :word => "soar", :definition => "rise fly high "
Word.create :word => "sober", :definition => "self-controlled "
Word.create :word => "sobriety", :definition => "quality or condition of being sober "
Word.create :word => "sodden", :definition => "soaked saturated "
Word.create :word => "soggy", :definition => "heavy with water "
Word.create :word => "solvent", :definition => "of the power of forming a solution "
Word.create :word => "somatic", :definition => "of the body "
Word.create :word => "soot", :definition => "black powder in smoke "
Word.create :word => "sophisticated", :definition => "complex subtle refined "
Word.create :word => "sophistry", :definition => "fallacious reasoning faulty logic "
Word.create :word => "sophomoric", :definition => "self-assured though immature affected bombastic overblown "
Word.create :word => "soporific", :definition => "producing sleep "
Word.create :word => "sordid", :definition => "wretched comfortless contemptible "
Word.create :word => "spear", :definition => "weapon with a metal point on a long shaft "
Word.create :word => "specious", :definition => "illogical of questionable truth or merit "
Word.create :word => "splenetic", :definition => "bad-tempered irritable "
Word.create :word => "splice", :definition => "join (two ends) "
Word.create :word => "sponge", :definition => "porous rubber for washing live at once expense "
Word.create :word => "spurious", :definition => "FALSE counterfeit "
Word.create :word => "spurn", :definition => "have nothing to do reject or refuse "
Word.create :word => "squalid", :definition => "foul filthy "
Word.create :word => "squander", :definition => "spend wastefully "
Word.create :word => "squat", :definition => "crouch/settle without permission "
Word.create :word => "stanch", :definition => "to stop the flow of a fluid "
Word.create :word => "steeply", :definition => "rising or falling sharply "
Word.create :word => "stentorian", :definition => "extremely loud and powerful "
Word.create :word => "stickler", :definition => "person who insists on importance of something"
Word.create :word => "stigma", :definition => "mark of shame or disgrace "
Word.create :word => "stigmatize", :definition => "describe smb scornfully "
Word.create :word => "sting", :definition => " something sharp "
Word.create :word => "stingy", :definition => "spending using unwillingly "
Word.create :word => "stint", :definition => "to be thrifty to set limits "
Word.create :word => "stipple", :definition => "paint with dots "
Word.create :word => "stipulate", :definition => "state or put forward as a necessary condition "
Word.create :word => "stolid", :definition => "showing no emotion impassive "
Word.create :word => "stray", :definition => "wander lose one's way "
Word.create :word => "streak", :definition => "long thin move very fast "
Word.create :word => "striated", :definition => "striped grooved or banded "
Word.create :word => "stride", :definition => "walk with long steps "
Word.create :word => "strut", :definition => "a supporting bar "
Word.create :word => "stygian", :definition => "hence dark gloomy "
Word.create :word => "stymie", :definition => "to hinder obstruct or block "
Word.create :word => "subdue", :definition => "overcome bring under control "
Word.create :word => "sublime", :definition => "extreme astounding "
Word.create :word => "submerge", :definition => "put under water liquid sink out of sight "
Word.create :word => "suborn", :definition => "induce by bribery or something to commit perjury "
Word.create :word => "subpoena", :definition => "written order requiring a person to appear in a low court "
Word.create :word => "substantiation", :definition => "giving facts to support (statement) "
Word.create :word => "subsume", :definition => "include under a rule "
Word.create :word => "succor", :definition => "assistance relief in time of distress "
Word.create :word => "suffice", :definition => "be enough "
Word.create :word => "suffocate", :definition => "cause or have difficulty in breathing "
Word.create :word => "sullied", :definition => "to be stained or discredited "
Word.create :word => "summarily", :definition => "briefly without delay "
Word.create :word => "sumptuous", :definition => "magnificent "
Word.create :word => "sundry", :definition => "various miscellaneous separate "
Word.create :word => "supercilious", :definition => "disdainful characterized by haughty scorn "
Word.create :word => "superfluous", :definition => "more then is needed or wanted "
Word.create :word => "superimpose", :definition => "put something on the top "
Word.create :word => "supersede", :definition => "take the place of "
Word.create :word => "supine", :definition => "lying on the back slow to act passive "
Word.create :word => "suppliant", :definition => "asking humbly beseeching "
Word.create :word => "supplicate", :definition => "make a humble petition to "
Word.create :word => "suppress", :definition => "prevent from being known put an end to "
Word.create :word => "surcharge", :definition => "additional load/charge "
Word.create :word => "surfeit", :definition => "satiate feed to fulness or to excess "
Word.create :word => "susceptibility", :definition => "sensitiveness "
Word.create :word => "swerve", :definition => "change direction suddenly "
Word.create :word => "sycophant", :definition => "person who flatter to the rich and powerful "
Word.create :word => "synopsis", :definition => "summary or outline "
Word.create :word => "taciturn", :definition => "untalkative silent "
Word.create :word => "tadpole", :definition => "form of a frog when it leaves the egg "
Word.create :word => "talon", :definition => "claw of a bird of prey "
Word.create :word => "tamp", :definition => "tap or drive down by repeated light blows "
Word.create :word => "tamper", :definition => "interfere with "
Word.create :word => "tangential", :definition => "suddenly changeable "
Word.create :word => "tarnished", :definition => "lost brightness "
Word.create :word => "tassel", :definition => "bunch of threads "
Word.create :word => "taunt", :definition => "contemptuous reproach hurtful remark "
Word.create :word => "taut", :definition => "tightly stretched "
Word.create :word => "tautology", :definition => "a repetition a redundancy "
Word.create :word => "tawdry", :definition => "cheap gaudy showy tacky "
Word.create :word => "teetotal", :definition => "oppose to alcohol "
Word.create :word => " telltale", :definition => " That gives warning or information"
Word.create :word => "temerity", :definition => "boldness brashness intrepidness "
Word.create :word => "temperance", :definition => "abstinence from alcohol self-control moderation "
Word.create :word => "temperate", :definition => "showing self-control "
Word.create :word => "tenacity", :definition => "firmness persistency adhesiveness tending to hang on "
Word.create :word => "tenuous", :definition => "insubstantial flimsy weak "
Word.create :word => "tepid", :definition => "lukewarm "
Word.create :word => "terse", :definition => "brief and to the point "
Word.create :word => "testiness", :definition => "witness/evidence "
Word.create :word => "thrift", :definition => "care economy thriving prosperous "
Word.create :word => "thwart", :definition => "obstruct/frustrate "
Word.create :word => "timid", :definition => "shy easily frightened "
Word.create :word => "timorous", :definition => "fearful timid afraid "
Word.create :word => "toady", :definition => "obsequious flatterer "
Word.create :word => "tonic", :definition => " something giving strength or energy "
Word.create :word => "topple", :definition => "be unsteady and overturn "
Word.create :word => "torment", :definition => "severe pain or suffering "
Word.create :word => "torpid", :definition => "sleeping sluggish lethargic dormant "
Word.create :word => "torque", :definition => "twisting force causing rotation "
Word.create :word => "tortuous", :definition => "devious/not straightforward "
Word.create :word => "tout", :definition => "person who worries others to buy something to use his service "
Word.create :word => "tractable", :definition => "easily controlled or guided "
Word.create :word => "transgress", :definition => "break go beyond (a limit) "
Word.create :word => "transient", :definition => "temporary fleeting "
Word.create :word => "transitory", :definition => "brief "
Word.create :word => "travesty", :definition => "parody/imitation "
Word.create :word => "trenchant", :definition => "forceful effective vigorous extremely perceptive incisive "
Word.create :word => "trepidation", :definition => "alarm excited state of mind "
Word.create :word => "trickle", :definition => "flow in drops "
Word.create :word => "trifling", :definition => "unimportant "
Word.create :word => "trite", :definition => "not new "
Word.create :word => "truce", :definition => "(agreement) stop of fighting for a time "
Word.create :word => "truculence", :definition => "aggressiveness ferocity "
Word.create :word => "trudge", :definition => "walk heavily "
Word.create :word => "turbid", :definition => "muddy having the sediment stirred up "
Word.create :word => "turbulence", :definition => "being uncontrolled violent "
Word.create :word => "turgid", :definition => "excessively ornate swollen or bloated "
Word.create :word => "turmoil", :definition => "trouble disturbance "
Word.create :word => "turpitude", :definition => "wickedness shamefulness "
Word.create :word => "turquoise", :definition => "greenish-blue precious stone "
Word.create :word => "tyro", :definition => "tiro beginner "
Word.create :word => "ubiquitous", :definition => "present everywhere "
Word.create :word => "ulterior", :definition => "situated beyond "
Word.create :word => "umbrage", :definition => "offense resentment "
Word.create :word => "uncouth", :definition => "rough awkward "
Word.create :word => "underbid", :definition => "make a lower bid then smb else "
Word.create :word => "undermine", :definition => "weaken gradually at the base make something under "
Word.create :word => "undulate", :definition => "to move in wavelike fashion fluctuate "
Word.create :word => "unearth", :definition => "discover and bring to light "
Word.create :word => "unencumbered", :definition => "easy-going trifle "
Word.create :word => "unfeigned", :definition => "not pretended sincere "
Word.create :word => "unscathed", :definition => "unharmed unhurt "
Word.create :word => "untoward", :definition => "unfortunate inconvenient "
Word.create :word => "upbraid", :definition => "scold reproach "
Word.create :word => "urbane", :definition => "elegant refined in manners "
Word.create :word => "vacillation", :definition => "being uncertain hesitating "
Word.create :word => "vagary", :definition => "strange act or idea "
Word.create :word => "vain", :definition => "without use result conceited "
Word.create :word => "valiant", :definition => "brave "
Word.create :word => "valorous", :definition => "brave "
Word.create :word => "vanquish", :definition => "conquer "
Word.create :word => " variegate", :definition => " To mark with different shade or colors"
Word.create :word => "veer", :definition => "change direction "
Word.create :word => "venal", :definition => "ready to do something dishonest "
Word.create :word => "veneer", :definition => "surface appearance covering the TRUE nature "
Word.create :word => "veneration", :definition => "regard with deep respect "
Word.create :word => "veracity", :definition => "truth "
Word.create :word => "verdant", :definition => "fresh and green "
Word.create :word => "verisimilitude", :definition => "appearing TRUE or real "
Word.create :word => "veritable", :definition => "real rightly named "
Word.create :word => "verve", :definition => "spirit vigor enthusiasm "
Word.create :word => "vestige", :definition => "trace or sign "
Word.create :word => "vex", :definition => "annoy distress trouble "
Word.create :word => "vigilance", :definition => "watchfulness self-appointed group who maintain order "
Word.create :word => "vigilant", :definition => "member of a vigilance committee "
Word.create :word => "vigorous", :definition => "strong energetic "
Word.create :word => "vilify", :definition => "slander say evil things "
Word.create :word => "vindictive", :definition => "having a desire to revenge "
Word.create :word => "virago", :definition => "a loud domineering woman a scold or nag "
Word.create :word => "visceral", :definition => "of the internal organs of the body "
Word.create :word => "viscous", :definition => "sticky/semi-fluid "
Word.create :word => "vitiate", :definition => "lower the quality weaken the strength "
Word.create :word => "vituperate", :definition => "curse abuse in words "
Word.create :word => "vivacious", :definition => "lively high-spirited "
Word.create :word => "volatile", :definition => "changeable inconstant fickle unstable explosive "
Word.create :word => "volubility", :definition => "fluency verbosity easy use of spoken language "
Word.create :word => "voluble", :definition => "fluent "
Word.create :word => "waffle", :definition => "talk vaguely and without much result "
Word.create :word => "waft", :definition => "scent waving movement carry lightly through "
Word.create :word => "wag", :definition => "merry person "
Word.create :word => "warmonger", :definition => "person who stirs up war "
Word.create :word => "warrant", :definition => "authority written order guarantee "
Word.create :word => "wean", :definition => "to turn away (from a habit) "
Word.create :word => "weigh", :definition => "measure hoe heavy something is "
Word.create :word => "welter", :definition => "turmoil a bewildering jumble "
Word.create :word => "wend", :definition => "to go proceed "
Word.create :word => "whimsical", :definition => "full of odd and fanciful ideas "
Word.create :word => "wince", :definition => "show bodily or mental pain "
Word.create :word => "woo", :definition => "try to win "
Word.create :word => "writ", :definition => "written order "
Word.create :word => "xenophile", :definition => " a person who is attracted to foreign peoples, cultures, or customs"
Word.create :word => "yarn", :definition => "tale story fibers for knitting "

# Set 'content' here as a full book corpus.
# This is really, really slow if you have a really big book.
# This is a lot of preprocessing.

content = ""

content = content.scan(/[^\.\?\!]+[\.\?\!]+[\n]*/)
allwords = Word.all
num = 0
for line in content
	a = BookLine.new(:line=>line,:linenum=>num)
	a.source = book.id
	a.save
	for word in allwords
		reg = /\b#{query}\b/i
		if (reg.match(line))
			wr = WordReference.new
			wr.word = word.id
			wr.bookline = a.id
		end
	end
	num=num+1
end

# Create some wordlists so we can actually play games.

wl = Wordlist.create
wl.name = "Wordlist 1"
wl.description = "A quick, sample word list for the game."
wl.words << Word.find(1)
wl.words << Word.find(2)
wl.words << Word.find(3)

